#!/usr/bin/env python
import time
import random
from termcolor import colored
text = input('What do you want to spam? ')
if text == 'minion':
    text = random.choice(open('minions').readlines())
elif text == 'minions':
    text = random.choice(open('minions').readlines())
try:
    interval = input('At what interval? (In seconds) ')
    if interval == '':
        interval = 0.075
    interval = float(interval)
    color = ['red', 'yellow', 'green', 'cyan', 'blue', 'magenta']
except ValueError:
    print("That is not an integer...")
else:
    while True:
        try:
            print(colored(text, color[0])),
            time.sleep(interval)
            print(colored(text, color[1])),
            time.sleep(interval)
            print(colored(text, color[2])),
            time.sleep(interval)
            print(colored(text, color[3])),
            time.sleep(interval)
            print(colored(text, color[4])),
            time.sleep(interval)
            print(colored(text, color[5]))
            time.sleep(interval)
        except KeyboardInterrupt:
            break
